# Generated by Django 5.2.1 on 2025-06-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountbook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gmailtransaction",
            name="category",
            field=models.CharField(default="未分類", max_length=50),
        ),
    ]
