# Generated by Django 5.2.1 on 2025-06-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountbook", "0002_gmailtransaction_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="gmailtransaction",
            name="tag",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
